"""
Comprehensive URL lists for medical articles from trusted sources.
Focus on diabetes and hypertension topics.
"""

MEDICAL_ARTICLE_URLS = {
    'Mayo Clinic': [
        # Diabetes
        'https://www.mayoclinic.org/diseases-conditions/type-2-diabetes/symptoms-causes/syc-20351193',
        'https://www.mayoclinic.org/diseases-conditions/type-2-diabetes/diagnosis-treatment/drc-20351199',
        'https://www.mayoclinic.org/diseases-conditions/type-2-diabetes/in-depth/diabetes/art-20043848',
        'https://www.mayoclinic.org/diseases-conditions/diabetes/in-depth/diabetes-management/art-20047963',
        'https://www.mayoclinic.org/diseases-conditions/diabetes/in-depth/diabetes-diet/art-20044295',
        'https://www.mayoclinic.org/diseases-conditions/diabetes/in-depth/diabetes-symptoms/art-20044248',
        'https://www.mayoclinic.org/diseases-conditions/diabetes/in-depth/diabetes-treatment/art-20051004',
        'https://www.mayoclinic.org/diseases-conditions/diabetes/expert-answers/diabetes/faq-20058461',
        'https://www.mayoclinic.org/diseases-conditions/diabetes/in-depth/diabetes-and-exercise/art-20045697',
        'https://www.mayoclinic.org/diseases-conditions/prediabetes/symptoms-causes/syc-20355278',
        'https://www.mayoclinic.org/diseases-conditions/type-1-diabetes/symptoms-causes/syc-20353011',
        'https://www.mayoclinic.org/diseases-conditions/diabetes/in-depth/diabetes-prevention/art-20047639',
        'https://www.mayoclinic.org/tests-procedures/a1c-test/about/pac-20384643',
        'https://www.mayoclinic.org/diseases-conditions/diabetes/in-depth/blood-sugar/art-20046628',
        'https://www.mayoclinic.org/diseases-conditions/diabetes/expert-answers/diabetes-and-depression/faq-20057904',
        # Hypertension
        'https://www.mayoclinic.org/diseases-conditions/high-blood-pressure/symptoms-causes/syc-20373410',
        'https://www.mayoclinic.org/diseases-conditions/high-blood-pressure/diagnosis-treatment/drc-20373417',
        'https://www.mayoclinic.org/diseases-conditions/high-blood-pressure/in-depth/high-blood-pressure-medication/art-20044451',
        'https://www.mayoclinic.org/diseases-conditions/high-blood-pressure/in-depth/blood-pressure/art-20050982',
        'https://www.mayoclinic.org/diseases-conditions/high-blood-pressure/in-depth/ace-inhibitors/art-20047480',
        'https://www.mayoclinic.org/diseases-conditions/high-blood-pressure/in-depth/calcium-channel-blockers/art-20047605',
        'https://www.mayoclinic.org/diseases-conditions/high-blood-pressure/in-depth/diuretics/art-20048129',
        'https://www.mayoclinic.org/diseases-conditions/high-blood-pressure/in-depth/beta-blockers/art-20044522',
        'https://www.mayoclinic.org/diseases-conditions/high-blood-pressure/expert-answers/blood-pressure/faq-20058115',
        'https://www.mayoclinic.org/diseases-conditions/high-blood-pressure/in-depth/high-blood-pressure/art-20046974',
        'https://www.mayoclinic.org/diseases-conditions/prehypertension/symptoms-causes/syc-20377150',
        'https://www.mayoclinic.org/tests-procedures/blood-pressure-test/about/pac-20393098',
        'https://www.mayoclinic.org/diseases-conditions/high-blood-pressure/in-depth/dash-diet/art-20048456',
        'https://www.mayoclinic.org/diseases-conditions/high-blood-pressure/expert-answers/white-coat-hypertension/faq-20057792',
        'https://www.mayoclinic.org/diseases-conditions/high-blood-pressure/expert-answers/hypertensive-crisis/faq-20058491',
    ],
    'Cleveland Clinic': [
        # Diabetes
        'https://my.clevelandclinic.org/health/diseases/21501-type-2-diabetes',
        'https://my.clevelandclinic.org/health/diseases/diabetes',
        'https://my.clevelandclinic.org/health/diseases/9012-prediabetes',
        'https://my.clevelandclinic.org/health/diseases/21500-type-1-diabetes',
        'https://my.clevelandclinic.org/health/diagnostics/12363-blood-glucose-test',
        'https://my.clevelandclinic.org/health/diagnostics/21952-hemoglobin-a1c-test',
        'https://my.clevelandclinic.org/health/diseases/22206-diabetes-complications',
        'https://my.clevelandclinic.org/health/treatments/24301-diabetes-medications',
        'https://my.clevelandclinic.org/health/articles/7104-oral-diabetes-medications',
        'https://my.clevelandclinic.org/health/drugs/20402-insulin',
        'https://my.clevelandclinic.org/health/diseases/21656-insulin-resistance',
        'https://my.clevelandclinic.org/health/diseases/21945-diabetic-ketoacidosis-dka',
        'https://my.clevelandclinic.org/health/diseases/21499-hyperglycemia-high-blood-sugar',
        'https://my.clevelandclinic.org/health/diseases/15729-hypoglycemia-low-blood-sugar',
        'https://my.clevelandclinic.org/health/articles/11443-diabetes-diet',
        # Hypertension
        'https://my.clevelandclinic.org/health/diseases/4314-hypertension-high-blood-pressure',
        'https://my.clevelandclinic.org/health/treatments/21480-hypertension-management-and-treatment',
        'https://my.clevelandclinic.org/health/diagnostics/16330-blood-pressure',
        'https://my.clevelandclinic.org/health/diseases/21156-prehypertension',
        'https://my.clevelandclinic.org/health/drugs/21512-ace-inhibitors',
        'https://my.clevelandclinic.org/health/drugs/21513-angiotensin-ii-receptor-blockers-arbs',
        'https://my.clevelandclinic.org/health/drugs/21514-beta-blockers',
        'https://my.clevelandclinic.org/health/drugs/21515-calcium-channel-blockers',
        'https://my.clevelandclinic.org/health/drugs/21516-diuretics',
        'https://my.clevelandclinic.org/health/diseases/21493-malignant-hypertension',
        'https://my.clevelandclinic.org/health/diseases/21967-secondary-hypertension',
        'https://my.clevelandclinic.org/health/diseases/21493-hypertensive-emergency',
        'https://my.clevelandclinic.org/health/articles/4249-dash-diet',
        'https://my.clevelandclinic.org/health/diseases/23010-labile-hypertension',
        'https://my.clevelandclinic.org/health/diseases/21156-masked-hypertension',
    ],
    'WebMD': [
        # Diabetes
        'https://www.webmd.com/diabetes/type-2-diabetes',
        'https://www.webmd.com/diabetes/default.htm',
        'https://www.webmd.com/diabetes/guide/diabetes-causes',
        'https://www.webmd.com/diabetes/guide/diabetes-symptoms',
        'https://www.webmd.com/diabetes/diabetes-types-of-insulin',
        'https://www.webmd.com/diabetes/guide/normal-blood-sugar-levels-chart-adults',
        'https://www.webmd.com/diabetes/guide/diabetes-diet-plan',
        'https://www.webmd.com/diabetes/ss/slideshow-diabetic-complications',
        'https://www.webmd.com/diabetes/prediabetes-overview',
        'https://www.webmd.com/diabetes/type-1-diabetes',
        'https://www.webmd.com/diabetes/a1c-test-diabetes',
        'https://www.webmd.com/diabetes/insulin-resistance-syndrome',
        'https://www.webmd.com/diabetes/guide/diabetes-hyperglycemia',
        'https://www.webmd.com/diabetes/guide/diabetes-hypoglycemia',
        'https://www.webmd.com/diabetes/features/diabetes-exercise-benefits',
        # Hypertension
        'https://www.webmd.com/heart/understanding-high-blood-pressure-basics',
        'https://www.webmd.com/hypertension-high-blood-pressure/guide/treatment-care',
        'https://www.webmd.com/hypertension-high-blood-pressure/guide/medications-blood-pressure',
        'https://www.webmd.com/hypertension-high-blood-pressure/guide/diastolic-and-systolic-blood-pressure-know-your-numbers',
        'https://www.webmd.com/hypertension-high-blood-pressure/ss/slideshow-hypertension-overview',
        'https://www.webmd.com/hypertension-high-blood-pressure/hypertension-symptoms-high-blood-pressure',
        'https://www.webmd.com/hypertension-high-blood-pressure/what-are-ace-inhibitors',
        'https://www.webmd.com/hypertension-high-blood-pressure/guide/beta-blockers',
        'https://www.webmd.com/hypertension-high-blood-pressure/guide/calcium-channel-blockers',
        'https://www.webmd.com/hypertension-high-blood-pressure/guide/diuretics-water-pills',
        'https://www.webmd.com/hypertension-high-blood-pressure/guide/dash-diet',
        'https://www.webmd.com/hypertension-high-blood-pressure/prehypertension-do-you-have-it',
        'https://www.webmd.com/hypertension-high-blood-pressure/guide/hypertensive-crisis',
        'https://www.webmd.com/hypertension-high-blood-pressure/features/exercise-to-lower-blood-pressure',
        'https://www.webmd.com/hypertension-high-blood-pressure/reduce-salt-sodium',
    ],
    'Healthline': [
        # Diabetes
        'https://www.healthline.com/health/type-2-diabetes',
        'https://www.healthline.com/health/diabetes',
        'https://www.healthline.com/health/type-2-diabetes-symptoms',
        'https://www.healthline.com/health/diabetes/medications-list',
        'https://www.healthline.com/health/diabetes/insulin-types',
        'https://www.healthline.com/health/diabetes-and-diet',
        'https://www.healthline.com/health/diabetes/complications',
        'https://www.healthline.com/health/prediabetes',
        'https://www.healthline.com/health/type-1-diabetes',
        'https://www.healthline.com/health/type-2-diabetes/ac1-test',
        'https://www.healthline.com/health/diabetes/insulin-resistance',
        'https://www.healthline.com/health/diabetes/hyperglycemia',
        'https://www.healthline.com/health/diabetes/hypoglycemia',
        'https://www.healthline.com/health/diabetes/diabetes-diet-best-foods',
        'https://www.healthline.com/health/diabetes/exercise',
        # Hypertension
        'https://www.healthline.com/health/high-blood-pressure-hypertension',
        'https://www.healthline.com/health/high-blood-pressure-hypertension/treatments',
        'https://www.healthline.com/health/high-blood-pressure-hypertension-medication',
        'https://www.healthline.com/health/high-blood-pressure-hypertension/symptoms',
        'https://www.healthline.com/health/high-blood-pressure-hypertension/causes',
        'https://www.healthline.com/health/ace-inhibitors',
        'https://www.healthline.com/health/beta-blockers',
        'https://www.healthline.com/health/calcium-channel-blockers',
        'https://www.healthline.com/health/diuretics',
        'https://www.healthline.com/health/dash-diet',
        'https://www.healthline.com/health/prehypertension',
        'https://www.healthline.com/health/hypertensive-crisis',
        'https://www.healthline.com/health/high-blood-pressure-diet',
        'https://www.healthline.com/health/high-blood-pressure-prevention',
        'https://www.healthline.com/health/fitness-exercise/blood-pressure-exercises-to-avoid',
    ],
    'NIH - NIDDK': [
        # Diabetes
        'https://www.niddk.nih.gov/health-information/diabetes/overview/what-is-diabetes',
        'https://www.niddk.nih.gov/health-information/diabetes/overview/what-is-diabetes/type-2-diabetes',
        'https://www.niddk.nih.gov/health-information/diabetes/overview/what-is-diabetes/type-1-diabetes',
        'https://www.niddk.nih.gov/health-information/diabetes/overview/what-is-diabetes/prediabetes-insulin-resistance',
        'https://www.niddk.nih.gov/health-information/diabetes/overview/symptoms-causes',
        'https://www.niddk.nih.gov/health-information/diabetes/overview/managing-diabetes',
        'https://www.niddk.nih.gov/health-information/diabetes/overview/diet-eating-physical-activity',
        'https://www.niddk.nih.gov/health-information/diabetes/overview/insulin-medicines-treatments',
        'https://www.niddk.nih.gov/health-information/diabetes/overview/preventing-problems',
        'https://www.niddk.nih.gov/health-information/diabetes/overview/preventing-problems/low-blood-glucose-hypoglycemia',
        'https://www.niddk.nih.gov/health-information/diabetes/overview/managing-diabetes/sick-days-special-situations',
        'https://www.niddk.nih.gov/health-information/diabetes/overview/tests-diagnosis',
        'https://www.niddk.nih.gov/health-information/diabetes/overview/preventing-type-2-diabetes',
        'https://www.niddk.nih.gov/health-information/diabetes/overview/managing-diabetes/continuous-glucose-monitoring',
        'https://www.niddk.nih.gov/health-information/diabetes/overview/managing-diabetes/know-blood-sugar-numbers',
    ],
    'CDC': [
        # Diabetes
        'https://www.cdc.gov/diabetes/basics/diabetes.html',
        'https://www.cdc.gov/diabetes/basics/type2.html',
        'https://www.cdc.gov/diabetes/basics/type1.html',
        'https://www.cdc.gov/diabetes/basics/prediabetes.html',
        'https://www.cdc.gov/diabetes/managing/manage-blood-sugar.html',
        'https://www.cdc.gov/diabetes/managing/eat-well.html',
        'https://www.cdc.gov/diabetes/managing/active.html',
        'https://www.cdc.gov/diabetes/managing/medication-management.html',
        'https://www.cdc.gov/diabetes/managing/diabetes-healthy-living.html',
        'https://www.cdc.gov/diabetes/prevent-type-2/index.html',
        'https://www.cdc.gov/diabetes/php/data-research/index.html',
        # Hypertension
        'https://www.cdc.gov/bloodpressure/about.htm',
        'https://www.cdc.gov/bloodpressure/facts.htm',
        'https://www.cdc.gov/bloodpressure/signs_symptoms.htm',
        'https://www.cdc.gov/bloodpressure/medication.htm',
        'https://www.cdc.gov/bloodpressure/prevent.htm',
        'https://www.cdc.gov/bloodpressure/lifestyle_changes.htm',
        'https://www.cdc.gov/bloodpressure/measure.htm',
        'https://www.cdc.gov/salt/index.htm',
        'https://www.cdc.gov/heartdisease/high_blood_pressure.htm',
    ],
    'American Diabetes Association': [
        'https://diabetes.org/about-diabetes/type-2',
        'https://diabetes.org/about-diabetes/symptoms',
        'https://diabetes.org/about-diabetes/medications',
        'https://diabetes.org/healthy-living/medication-treatments/insulin-and-other-injectables',
        'https://diabetes.org/healthy-living/medication-treatments/oral-medication',
        'https://diabetes.org/healthy-living/recipes-nutrition',
        'https://diabetes.org/healthy-living/fitness',
        'https://diabetes.org/about-diabetes/diagnosis',
        'https://diabetes.org/about-diabetes/prediabetes',
        'https://diabetes.org/about-diabetes/type-1',
    ],
    'American Heart Association': [
        'https://www.heart.org/en/health-topics/high-blood-pressure',
        'https://www.heart.org/en/health-topics/high-blood-pressure/understanding-blood-pressure-readings',
        'https://www.heart.org/en/health-topics/high-blood-pressure/the-facts-about-high-blood-pressure',
        'https://www.heart.org/en/health-topics/high-blood-pressure/changes-you-can-make-to-manage-high-blood-pressure',
        'https://www.heart.org/en/health-topics/high-blood-pressure/health-threats-from-high-blood-pressure',
        'https://www.heart.org/en/health-topics/high-blood-pressure/why-high-blood-pressure-is-a-silent-killer',
        'https://www.heart.org/en/health-topics/high-blood-pressure/prevention-treatment-of-high-blood-pressure',
    ],
    'Johns Hopkins Medicine': [
        'https://www.hopkinsmedicine.org/health/conditions-and-diseases/diabetes/diabetes-and-high-blood-pressure',
        'https://www.hopkinsmedicine.org/health/conditions-and-diseases/diabetes',
        'https://www.hopkinsmedicine.org/health/wellness-and-prevention/type-2-diabetes-the-basics',
        'https://www.hopkinsmedicine.org/health/conditions-and-diseases/high-blood-pressure-hypertension',
    ],
    'MedlinePlus': [
        'https://medlineplus.gov/diabetestype2.html',
        'https://medlineplus.gov/diabetes.html',
        'https://medlineplus.gov/prediabetes.html',
        'https://medlineplus.gov/diabetesmedicines.html',
        'https://medlineplus.gov/highbloodpressure.html',
        'https://medlineplus.gov/highbloodpressuremedicines.html',
        'https://medlineplus.gov/howtopreventhighbloodpressure.html',
    ],
}
